name: feather_client
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  intl: ^0.18.0
  window_manager: ^0.3.1
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.7
  file_selector: ^1.0.0
  uuid: ^3.0.6
  crypto: ^3.0.3
  provider: ^5.0.0
  flutter_client_sse: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Graphik
    fonts:
      - asset: assets/fonts/Graphik.ttc
